name: Start Server

on:
  workflow_run:
    workflows: [Deploy back-end aplication on EC2]
    types:
      - completed

jobs:
  startServer:
    runs-on: ubuntu-latest

    steps:
    - name: start server nest
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: chmod u+x ./${{ secrets.USERNAME }}/restart.sh &
